---
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: hello
          image: busybox
          command:
            - sh
            - -c
            - echo "Hello, Kubernetes!"
      restartPolicy: OnFailure
