# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=70)),
                ('text', models.TextField(verbose_name='Kommentartext')),
            ],
        ),
        migrations.CreateModel(
            name='Meldung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('zeitstempel', models.DateTimeField()),
                ('text', models.TextField(verbose_name='Meldungstext')),
            ],
        ),
        migrations.AddField(
            model_name='kommentar',
            name='meldung',
            field=models.ForeignKey(on_delete=models.CASCADE, to='news.Meldung'),
        ),
    ]
