---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Deploy 'hello' Job.
      k8s:
        state: present
        definition: "{{ lookup('file', 'manifests/hello.yml') }}"
        wait: true
