#!/bin/sh
# Name: ssh_tar
# Backups mit tar über ssh

# Konfiguration, entsprechend anpassen
#
SSH_OPT="-l"
SSH_HOST="192.135.147.2"
SSH_USER="jwolf"

# Default-Angaben
#
LOCAL_DIR="/home/tot/backups"
REMOTE_DIR="/home/jwolf/backups"
stamp=`date +%d_%m_%Y`
BACKUP_FILE="backup_${stamp}.tgz"

usage() {
   echo "usage: star [-ph] [-pl] [-sh] [-sl] [-r] [-l] ..."
   echo 
   echo "Optionen : "
   echo " –ph : (lokales) Verzeichnis packen und hochladen " \
        " (remote) in 'REMOTE_DIR'"
   echo "     Beispiel:   star -ph lokalesVerzeichnis "
   echo " -pl = (remote) Verzeichnis Packen und runterladen"\
        " (lokal) in 'LOCAL_DIR'"
   echo "     Beispiel:   star -pl remoteVerzeichnis "
   echo " -sh = Synchronisiert ein Host-Verzeichnis mit einem "\
        "lokalen Verzeichnis"
   echo "     Beispiel:   star -sh lokalesVerzeichnis "\
        "remoteVerzeichnis syncVerzeichnis "
   echo " -sl = Synchronisiert ein lokales Verzeichnis mit "\
        "einem Host-Verzeichnis"
   echo "     Beispiel:   star -sl remoteVerzeichnis "\
        "lokalesVerzeichnis syncVerzeichnis "   
   echo " -r  = (remote) Wiederherstellen eines"\
        " Host-Verzeichnisses"
   echo "     Beispiel:   star -r remoteVerzeichnis "\
        "lokalTarArchiv.tgz"
   echo " -l  = (lokal)  Wiederherstellen eines lokalen "\
        "Verzeichnisses"
   echo "     Beispiel:   star -l lokalesVerzeichnis "\
        "remoteTarArchiv.tgz"
   # ...
   exit 1
}

case "$1" in
    -ph)
       if [ $# -ne 2 ]
       then
          usage
       else
          cd $2; tar zcvf - "." | \
          ssh $SSH_OPT $SSH_USER $SSH_HOST \
          "cat > ${REMOTE_DIR}/${BACKUP_FILE}" 
          echo "Verzeichnis '$2' nach "\
               "${SSH_HOST}:${REMOTE_DIR}/${BACKUP_FILE} "\
               "gesichert"  
       fi ;;  
    -pl)
       if [ $# -ne 2 ]
       then 
          usage
       else
          ssh $SSH_OPT $SSH_USER $SSH_HOST \
          "cd $2; tar zcvf - ." | \
          cat > ${LOCAL_DIR}/${BACKUP_FILE}
          echo "Verzeichnis ${SSH_HOST}:${2} nach "\
               "${LOCAL_DIR}/${BACKUP_FILE} gesichert"  
       fi ;;  
    -sh)
       if [ $# -ne 4 ]
       then
          usage
       else
          cd $2
          tar zcf - $4/ |
          ssh $SSH_OPT $SSH_USER $SSH_HOST \
          "cd $3; mv $4 ${4}.bak; tar zpxvf -" 
          echo "Verzeichnis ${2}/${4} mit"\
               " ${SSH_HOST}:${3}/${4} synchronisiert"    
       fi ;;  
    -sl)
       if [ $# -ne 4 ]
       then
          usage
       else    
          cd $3; mv $4 ${4}.bak
     ssh $SSH_OPT $SSH_USER $SSH_HOST "cd ${2}; tar zcvf - ${4}"\
     | tar zpvxf - 
          echo "Verzeichnis ${SSH_HOST}:${2}/${4} mit"\
               " ${3}/${4} synchronisiert"  
       fi ;;         
    -r) 
       if [ $# -ne 3 ]
       then
          usage
       else
          ssh $SSH_OPT $SSH_USER $SSH_HOST \
          "cd ${2}; tar zpvxf -" < $3 
          echo "${SSH_HOST}:$2 mit dem Archiv $3 "\
               "Wiederhergestellt"  
       fi ;;
    -l) 
       if [ $# -ne 3 ]
       then
          usage
       else
          cd $2
          ssh $SSH_OPT $SSH_USER $SSH_HOST "cat $3" | \
          tar zpvxf -
          echo "$2 mit dem Archiv ${SSH_HOST}:${3} "\
               "Wiederhergestellt"
       fi ;; 
    -*)   usage;;
     *)   usage;;
esac