#!/bin/sh
# Name: sshell
# Kommandos bzw. Scripts auf entfernten Rechner ausführen

# ggf. den Pfad zur Datei anpassen
HOSTS="hostlist.txt"

usage() {
   echo "usage: progname [-option] [Verzeichnis] "\
        " Kommando_oder_Script"
   echo
   echo "Option:"
   echo "-d :in ein bestimmtes Verzeichnis auf dem Host wechseln"
   echo "-s :Script in ein bestimmtes Verzeichnis hochladen und"\
        " Ausführen"
   echo
   echo "Syntax der Host-Liste: "
   echo "Username@hostname1"
   echo "Username@hostname2"
   echo "..."
   exit 1
}

if [ $# -eq 0 ]
then
   usage
fi

# Datei 'hostlist.txt' überprüfen
if [ -e $HOSTS ]
then :
else
   echo "Datei $HOSTS existiert nicht ..."
   touch hostlist.txt
   if [ $? -ne 0 ]
   then
      echo "Konnte $HOSTS nicht anlegen ...!"
      exit 1
   else
      echo "Datei $HOSTS erzeugt, aber noch leer ...!"
      usage
      exit 1
   fi
fi

# Optionen überprüfen ...
case $1 in
   -d)   
      if [ $# -lt 3 ]
      then
         usage
      fi
      DIR=$2
      shift; shift  ;;
   -s)  
      if [ $# -lt 3 ]
      then
         usage
      fi
      DIR=$2
      SCRIPT="yes"
      shift; shift  ;;       
   -*)
      usage ;;      
esac

# Die einzelnen Hosts durchlaufen ...
for host in `cat $HOSTS`
do
   echo "$host : "
   CMD=$*
   
   if [ "$SCRIPT" = "yes" ]
   then
      scp $CMD ${host}:${DIR}
   fi
   
   ret=`ssh $host "cd $DIR; $CMD"`
   echo "$ret"
done